version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.6-jessie-browsers
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: hi-database
    working_directory: ~/Hirola
    
    steps:
      - checkout
      - run:
          name: run tests
          environment:
            SECRET_KEY: "simplestring"
            DJANGO_SETTINGS_MODULE: hirola.settings.development
            POSTGRES_IP: 127.0.0.1
            PGUSER: root
            DATABASE_NAME: hi-database
            USER: postgres
          command: |
            sudo apt-get install memcached
            memcached -d
            virtualenv --python=python3 hi-venv
            source hi-venv/bin/activate
            pip install -r ./hirola/requirements.txt
            python ./hirola/manage.py makemigrations front
            python ./hirola/manage.py migrate
            cd hirola && python manage.py test
          

  application-deployment:
    docker:
      - image: circleci/python:3.6-jessie-browsers
    steps:
      - checkout
      - run: bash .circleci/deploy.sh

workflows:
  version: 2
  deploy-application:
    jobs:
      - test
      - application-deployment:
          requires:
            - test
