version: 2
jobs:
  application-deployment:
    docker:
      - image: circleci/python:3.6-jessie-browsers
    steps:
      - checkout
      - run: bash .circleci/deploy.sh

workflows:
  version: 2
  deploy-application:
    jobs:
      - application-deployment
