# Generated by Django 2.0.2 on 2019-02-14 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import front.models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_one', models.CharField(max_length=255)),
                ('address_line_two', models.CharField(max_length=255)),
                ('address_line_three', models.CharField(blank=True, max_length=255, null=True)),
                ('short_description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('total_price', front.models.IntegerRangeField(default=0)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='front.PaymentMethod')),
            ],
        ),
        migrations.CreateModel(
            name='RepairService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ServicePerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('name_of_premise', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(blank=True, error_messages={'unique': 'The email address you entered has already been registered.'}, max_length=255, null=True, unique=True, verbose_name='email address')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='front.Address')),
                ('country_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='front.CountryCode')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='front.RepairService')),
                ('service_man', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='front.ServicePerson')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=0, default=100000, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='phonescolor',
            name='price',
            field=models.DecimalField(decimal_places=0, default=10000, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phonescolor',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='front.PhoneMemorySize'),
        ),
        migrations.AlterField(
            model_name='order',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='phonescolor',
            name='is_in_stock',
            field=models.BooleanField(default=False, help_text='Designates whether this phone                                               color is in stock. Unselect this instead of                                               deleting phone color.', verbose_name='in_stock'),
        ),
        migrations.AlterUniqueTogether(
            name='phonescolor',
            unique_together={('phone', 'size')},
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='front.Cart'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='services',
            unique_together={('service', 'service_man')},
        ),
    ]
