# Generated by Django 2.0.2 on 2019-03-05 06:12

from django.db import migrations, models
import django.db.models.deletion
import front.models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_auto_20190214_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(error_messages={'unique': 'The brand name you entered already exists'}, max_length=255, unique=True)),
                ('brand_icon', models.CharField(blank=True, default='', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_model', models.CharField(error_messages={'unique': 'The brand model you entered already exists'}, max_length=255, unique=True)),
                ('average_review', models.DecimalField(decimal_places=1, default=5.0, max_digits=2)),
                ('brand_model_image', models.ImageField(default='brand_model_image_alt', upload_to='brand_models')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='front.PhoneBrand')),
            ],
            options={
                'verbose_name_plural': 'PhoneModels',
            },
        ),
        migrations.CreateModel(
            name='PhoneModelList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, max_digits=6)),
                ('quantity', front.models.IntegerRangeField()),
                ('is_in_stock', models.BooleanField(default=False, help_text='Designates whether this phone color is in stock. Unselect this instead of deleting phone color.', verbose_name='in_stock')),
                ('main_image', models.ImageField(upload_to='phones')),
            ],
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='date',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='updated',
            new_name='modified_date',
        ),
        migrations.RemoveField(
            model_name='phoneimage',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='review',
            name='phone',
        ),
        migrations.AddField(
            model_name='phonecategory',
            name='category_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='front.ItemIcon'),
        ),
        migrations.AlterField(
            model_name='color',
            name='color',
            field=models.CharField(error_messages={'unique': 'The color you entered already exists'}, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='feature',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='feature',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_features', to='front.PhoneModelList'),
        ),
        migrations.AlterField(
            model_name='hotdeal',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.PhoneModelList'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='front.Cart'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.PhoneModelList'),
        ),
        migrations.AlterField(
            model_name='productinformation',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_information', to='front.PhoneModelList'),
        ),
        migrations.AddField(
            model_name='phonemodellist',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phone_color', to='front.Color'),
        ),
        migrations.AddField(
            model_name='phonemodellist',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='front.Currency'),
        ),
        migrations.AddField(
            model_name='phonemodellist',
            name='phone_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_list', to='front.PhoneModel'),
        ),
        migrations.AddField(
            model_name='phonemodellist',
            name='size_sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phone_size', to='front.PhoneMemorySize'),
        ),
        migrations.AddField(
            model_name='phonemodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='front.PhoneCategory'),
        ),
        migrations.AddField(
            model_name='phoneimage',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phone_images', to='front.PhoneModelList'),
        ),
        migrations.AddField(
            model_name='review',
            name='phone_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='phone_reviews', to='front.PhoneModel'),
            preserve_default=False,
        ),
    ]
