# Generated by Django 2.0.2 on 2019-02-17 12:51

from django.db import migrations, models
import django.db.models.deletion
import front.models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_auto_20190217_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(error_messages={'unique': 'The brand name you entered already exists'}, max_length=255, unique=True)),
                ('brand_icon', models.CharField(blank=True, default='', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_model', models.CharField(error_messages={'unique': 'The brand model you entered already exists'}, max_length=255, unique=True)),
                ('average_review', models.DecimalField(decimal_places=1, default=5.0, max_digits=2)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='front.PhoneCategory')),
            ],
            options={
                'verbose_name_plural': 'PhoneModels',
            },
        ),
        migrations.CreateModel(
            name='PhoneModelList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, max_digits=6)),
                ('main_image', models.ImageField(upload_to='phones')),
                ('quantity', front.models.IntegerRangeField()),
                ('is_in_stock', models.BooleanField(default=False, help_text='Designates whether this phone color is in stock. Unselect this instead of deleting phone color.', verbose_name='in_stock')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='front.Color')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='front.Currency')),
                ('phone_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.PhoneModel')),
                ('size_sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='front.PhoneMemorySize')),
            ],
        ),
    ]
