# Generated by Django 2.0.2 on 2019-02-14 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_auto_20190214_2024'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Addresses',
            new_name='Address',
        ),
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='serviceperson',
            options={'verbose_name_plural': 'ServicePeople'},
        ),
        migrations.RenameField(
            model_name='repairservice',
            old_name='service',
            new_name='repair_service',
        ),
    ]
