# Generated by Django 2.0.2 on 2019-02-17 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_phonebrand_phonemodel_phonemodellist'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonemodel',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='front.PhoneBrand'),
        ),
    ]
