# Generated by Django 2.0.2 on 2019-03-08 09:03

from django.db import migrations, models
import django.db.models.deletion
import front.models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_auto_20190305_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
        migrations.AddField(
            model_name='cart',
            name='phone_model_item',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='front.PhoneModelList'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=front.models.IntegerRangeField(default=0),
            preserve_default=False,
        ),
    ]
