# Generated by Django 2.0.2 on 2019-03-12 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0006_cart_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
    ]
