# Generated by Django 2.0.2 on 2019-02-17 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0007_auto_20190217_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonecategory',
            name='category_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='front.ItemIcon'),
        ),
        migrations.AlterField(
            model_name='hotdeal',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.PhoneModelList'),
        ),
    ]
