# Generated by Django 2.0.2 on 2019-03-16 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0008_auto_20190309_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_wishlist',
            field=models.BooleanField(default=False, help_text='Designates whether cart is to be added to the wish list', verbose_name='wish list'),
        ),
    ]
