# Generated by Django 2.0.2 on 2019-03-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0009_auto_20190304_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinformation',
            name='feature',
            field=models.CharField(max_length=256),
        ),
    ]
