# Generated by Django 2.0.2 on 2019-04-05 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0010_cartowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='phone_size_sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='front.PhoneMemorySize'),
        ),
    ]
