# Generated by Django 2.0.2 on 2019-03-04 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0010_auto_20190304_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.PhoneModelList'),
        ),
    ]
