# Generated by Django 2.0.2 on 2019-04-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0011_cart_phone_size_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='phone_size_sku',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
