# Generated by Django 2.0.2 on 2019-04-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0013_auto_20190405_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='phone_size_sku',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='size',
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(default='processing', error_messages={'unique': 'The status you entered already exists'}, max_length=60, unique=True),
        ),
    ]
