# Generated by Django 2.0.2 on 2019-07-05 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import front.models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0017_shippingaddress_country_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelledOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantity', front.models.IntegerRangeField()),
                ('total_price', front.models.IntegerRangeField(default=0)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='front.PaymentMethod')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.PhoneModelList')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.ShippingAddress')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.OrderStatus')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-date',)},
        ),
        migrations.AddField(
            model_name='order',
            name='is_cancellable',
            field=models.BooleanField(default=True, help_text="Designates whether an order's window forbeing cancelled has expired", verbose_name='is_cancellable'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
